Repository fluix/apidoc2ts, pull requests merged in 2019-10, with the labels that each got.

#69 Update git hook for branch name checking
  .git-scripts/check-branch-name.js
  CONTRIBUTING.md
Labels: Frontend, enhancement

#74 Change source argument purpose.
  src/cli/Index.ts
  src/core/ApiDoc2Interface.test.ts
  src/core/ApiDoc2Interface.ts
Labels: Frontend, improvement

#73 Update npm package info
  package.json
Labels: Frontend

#75 TSLint -> ESLint migration
  .eslintrc.js
  package-lock.json
  package.json
  src/cli/Index.ts
  src/cli/InputParser.ts
  src/core/ApiDoc2Interface.test.ts
  src/core/ApiDoc2Interface.ts
  src/core/JsonSchema.ts
  src/core/endpoint-converter/ApiDocToInterfaceConverter.test.ts
  src/core/endpoint-converter/ApiDocToInterfaceConverter.ts
  src/core/endpoint-parser/ApiDocExamplesParser.ts
  src/core/endpoint-parser/ApiDocFieldsParser.test.ts
  src/core/endpoint-parser/ApiDocFieldsParser.ts
  src/core/interface-generator/InterfaceGenerator.test.ts
  src/core/interface-generator/InterfaceGenerator.ts
  src/core/interfaces-writer/InterfacesWriter.ts
  src/core/interfaces-writer/UrlStructureInterfacesWriter.ts
  src/core/utils/FsUtils.ts
  src/core/utils/StringUtils.ts
  src/core/utils/WriterUtils.ts
  tslint.json
Labels: Frontend
